### PR TITLE
Achivement link task complete with some Lazy loading changes

### PR DESCRIPTION
**Pull request by shiva-infobeans**

### CODE REVIEW

**Comment by rsonar-infobeans** [comment]
Alignment issues:

issue2
issue1

**Comment by rsonar-infobeans** [comment]
@shiva-infobeans check my comments above.

**Comment by rsonar-infobeans** [comment]
issue4
One more issue

**Comment by rsonar-infobeans** [comment]
issue5

**Comment by shiva-infobeans** [comment]
I solved the issues.

**Pull request merged**
